/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_vincentwinner_toolset_ai_seeta6jni_FaceLandmark68 */

#ifndef _Included_io_vincentwinner_toolset_ai_seeta6jni_FaceLandmark68
#define _Included_io_vincentwinner_toolset_ai_seeta6jni_FaceLandmark68
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_vincentwinner_toolset_ai_seeta6jni_FaceLandmark68
 * Method:    loadModel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_vincentwinner_toolset_ai_seeta6jni_FaceLandmark68_loadModel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_vincentwinner_toolset_ai_seeta6jni_FaceLandmark68
 * Method:    mark
 * Signature: (Lio/vincentwinner/toolset/ai/seeta6jni/structs/SeetaImageData;Lio/vincentwinner/toolset/ai/seeta6jni/structs/SeetaRect;)[Lio/vincentwinner/toolset/ai/seeta6jni/structs/SeetaPointF;
 */
JNIEXPORT jobjectArray JNICALL Java_io_vincentwinner_toolset_ai_seeta6jni_FaceLandmark68_mark
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
