/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_vincentwinner_toolset_ai_seeta6jni_FaceRecognizer */

#ifndef _Included_io_vincentwinner_toolset_ai_seeta6jni_FaceRecognizer
#define _Included_io_vincentwinner_toolset_ai_seeta6jni_FaceRecognizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_vincentwinner_toolset_ai_seeta6jni_FaceRecognizer
 * Method:    loadModel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_vincentwinner_toolset_ai_seeta6jni_FaceRecognizer_loadModel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_vincentwinner_toolset_ai_seeta6jni_FaceRecognizer
 * Method:    extractFaceFeature
 * Signature: (Lio/vincentwinner/toolset/ai/seeta6jni/structs/SeetaImageData;[Lio/vincentwinner/toolset/ai/seeta6jni/structs/SeetaPointF;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_io_vincentwinner_toolset_ai_seeta6jni_FaceRecognizer_extractFaceFeature
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     io_vincentwinner_toolset_ai_seeta6jni_FaceRecognizer
 * Method:    compare
 * Signature: ([F[F)F
 */
JNIEXPORT jfloat JNICALL Java_io_vincentwinner_toolset_ai_seeta6jni_FaceRecognizer_compare
  (JNIEnv *, jobject, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
