/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_vincentwinner_toolset_ai_seeta6jni_PoseEstimation */

#ifndef _Included_io_vincentwinner_toolset_ai_seeta6jni_PoseEstimation
#define _Included_io_vincentwinner_toolset_ai_seeta6jni_PoseEstimation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_vincentwinner_toolset_ai_seeta6jni_PoseEstimation
 * Method:    loadModel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_vincentwinner_toolset_ai_seeta6jni_PoseEstimation_loadModel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_vincentwinner_toolset_ai_seeta6jni_PoseEstimation
 * Method:    estimationPose
 * Signature: (Lio/vincentwinner/toolset/ai/seeta6jni/structs/SeetaImageData;Lio/vincentwinner/toolset/ai/seeta6jni/structs/SeetaFaceInfo;)Lio/vincentwinner/toolset/ai/seeta6jni/structs/SeetaAngle;
 */
JNIEXPORT jobject JNICALL Java_io_vincentwinner_toolset_ai_seeta6jni_PoseEstimation_estimationPose
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
